home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home')
]

profiles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.profile, name='profile'),
    path('order_history/<order_number>',
         views.order_history, name='order_history'),
]

stumps_and_studs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('basket/', include('basket.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from decimal import Decimal
from django.conf import settings

from django_countries.fields import CountryField

from products.models import Product
from profiles.models import UserProfile


class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(
        UserProfile, on_delete=models.SET_NULL,
        null=True, blank=True, related_name='orders')
    order_date = models.DateTimeField(auto_now_add=True)
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    county = models.CharField(max_length=80, null=True, blank=True)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    country = CountryField(
        blank_label='Country - Please Select *', null=False, blank=False)
    delivery_cost = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    original_basket = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(
        max_length=254, null=False, blank=False, default='')

    def _generate_order_number(self):
        """ Generate a random and unique order number using UUID. """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """ Update order total & grand total of order
        each time a new item is added to order. """
        self.order_total = self.lineitems.aggregate(
            Sum('lineitem_total'))['lineitem_total__sum'] or 0
        self.delivery_cost = settings.STANDARD_DELIVERY_COST
        self.grand_total = self.order_total + Decimal(str(self.delivery_cost))
        self.save()

    def save(self, *args, **kwargs):
        """ Overide the original save method to set the order number if
        it doesn't have one already. """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    size_choices = [
        (None, 'No Side'),
        ('jr', 'Junior'),
        ('xs', 'Extra Small'),
        ('s', 'Small'),
        ('m', 'Medium'),
        ('l', 'Large'),
        ('xl', 'Extra Large'),
    ]
    side_choices = [
        (None, 'No Side'),
        ('right', 'Right-Handed'),
        ('left', 'Left-Handed'),
    ]

    gender_choices = [
        (None, 'No Gender'),
        ('male', 'Male'),
        ('female', 'Female'),
    ]

    order = models.ForeignKey(
        Order, null=False, blank=False,
        on_delete=models.CASCADE, related_name='lineitems')
    product = models.ForeignKey(
        Product, null=False, blank=False, on_delete=models.CASCADE)
    product_size = models.CharField(
        max_length=2, choices=size_choices,
        default=None, blank=True, null=True)  # "", JR, XS, S, M, L, XL
    product_side = models.CharField(
        max_length=12, choices=side_choices,
        default=None, blank=True, null=True)  # "", right, left
    product_gender = models.CharField(
        max_length=10, choices=gender_choices,
        default=None, blank=True, null=True)  # "", male, female
    qty = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False,
        blank=False, editable=False)

    def save(self, *args, **kwargs):
        """ Overide the original save method to set the
        lineitem total and update the order total. """
        self.lineitem_total = self.product.price * self.qty
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

from django_countries.fields import CountryField


class UserProfile(models.Model):
    """ User Profiles with 1 to 1 relationship
    with built-in Django User model """

    class Meta:
        verbose_name_plural = 'User Profiles'

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    default_phone_number = models.CharField(
        max_length=20, null=True, blank=True)
    default_street_address1 = models.CharField(
        max_length=80, null=True, blank=True)
    default_street_address2 = models.CharField(
        max_length=80, null=True, blank=True)
    default_town_or_city = models.CharField(
        max_length=40, null=True, blank=True)
    default_county = models.CharField(max_length=80, null=True, blank=True)
    default_postcode = models.CharField(max_length=20, null=True, blank=True)
    default_country = CountryField(
        blank_label='Country - Please Select', null=True, blank=True)

    def __str__(self):
        return self.user.username

    @receiver(post_save, sender=User)
    def create_or_update_user_profile(sender, instance, created, **kwargs):
        """ Create or update the user profile """
        if created:
            UserProfile.objects.create(user=instance)
        # Existing users: save the profile
        instance.userprofile.save()

profiles/forms.py
from django import forms
from .models import UserProfile


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        """ Customise placeholders, add classes, remove auto-generated
        labels and set autofocus on the first field (Phone Number). """
        super().__init__(*args, **kwargs)
        # Create a dictionary of placeholders where:
        # key = field, value = placeholder.
        placeholders = {
            'default_phone_number': 'Phone Number',
            'default_street_address1': 'Street Address 1',
            'default_street_address2': 'Street Address 2',
            'default_town_or_city': 'Town/City',
            'default_county': 'County',
            'default_postcode': 'Postcode',
        }

        # Set the autofocus to the phone number field
        self.fields['default_phone_number'].widget.attrs['autofocus'] = True

        # Loop through all fields.
        for field in self.fields:
            if field != 'default_country':
                # If the field is required, add asterix to placeholder.
                if self.fields[field].required:
                    placeholder = f'{placeholders[field]} *'
                else:
                    placeholder = f'{placeholders[field]}'
                # Set the placeholder attribute to
                # the placeholder created above.
                self.fields[field].widget.attrs['placeholder'] = placeholder
            self.fields[field].widget.attrs['class'] = 'stripe-style-input'
            # Remove the field labels.
            self.fields[field].label = False

profiles/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.contrib .auth.decorators import login_required

from .models import UserProfile
from .forms import UserProfileForm

from checkout.models import Order


@login_required
def profile(request):
    """ Display the user's profile. """
    profile = get_object_or_404(UserProfile, user=request.user)

    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'Default delivery information \
                successfully updated.')
        else:
            messages.error(request, 'Update failed.  Please ensure the \
                form is valid.')
    else:
        form = UserProfileForm(instance=profile)

    # Retrieve all orders linked to this profile and sort by order date
    # with the most recent orders first (newest to oldest).
    orders = profile.orders.all().order_by('-order_date')

    template = 'profiles/profile.html'
    context = {
        'form': form,
        'orders': orders,
    }

    return render(request, template, context)


def order_history(request, order_number):
    order = get_object_or_404(Order, order_number=order_number)

    messages.info(request, (
        f'This is a past confirmation for order number {order_number}.  \
            A confirmation email was sent on the order date.'
    ))

    template = 'checkout/checkout_success.html'
    context = {
        'order': order,
        'from_profile': True
    }

    return render(request, template, context)

profiles/templates/profiles/profile.html
{% extends "base.html" %}
{% load static %}
{% block head_title %}| My Account{% endblock %}

{% block extra_meta %}
    <meta name="description" content="Stumps & Studs - view your account details before buying our range of the latest sports equipment, clothing and footwear.">
{% endblock %}

{% block content %}
    <div class="container-fluid px-3 px-sm-5 py-5">
        <div class="row">
            <div class="col-12 px-3">
                <h2 class="mb-4">My Account</h2>
            </div>
        </div>
        <div class="row">
            <!-- Default Delivery Information -->
            <div class="col-12 col-md-6 px-md-4">
                <h5 class="px-3">Default Delivery Information</h5>
                <div class="px-2">
                    <hr class="hr-black mt-0">
                </div>
                <form action="{% url 'profile' %}" method="POST" id="profile-update-form" class="black-border p-2 p-sm-4 mb-5 mb-md-4">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="d-flex flex-wrap justify-content-evenly align-items-center py-3">
                        <input type="submit" id="update-defaults" class="btn btn-green py-2 w-100 border-0 mt-3 ms-0" value="Update">
                    </div>
                </form>
                <!-- Change Password -->
                <h5 class="px-3">Change Account Password</h5>
                <div class="px-2">
                    <hr class="hr-black mt-0">
                </div>
                <div class="black-border p-2 p-sm-4 mb-5 mb-md-4">
                    <p class="fs-small">Need to change your password?:</p>
                    <div class="text-center">
                        <a class="btn btn-green py-2 w-100" href="{% url 'account_change_password' %}">
                            <h5 class="mb-0">Change Password</h5>
                        </a>
                    </div>
                </div>
            </div>
            <!-- Order History -->
            <div class="col-12 col-md-6 mt-5 mt-md-0 px-md-4">
                <h5 class="px-3">Order History</h5>
                <div class="px-2">
                    <hr class="hr-black mt-0">
                </div>
                <div class="black-border p-2 p-sm-4 mb-5 mb-md-4">
                    {% if orders %}
                        {% for order in orders %}
                            <!-- Order Number -->
                            <div class="d-flex align-items-center justify-content-between">
                                <h5 class="mb-1 d-inline">View Order:</h5>
                                <a class="text-decoration-underline text-end" href="{% url 'order_history' order.order_number %}" title="{{ order.order_number }}">
                                    <span>{{ order.order_number|truncatechars:16 }}</span>
                                </a>
                            </div>
                            <!-- Order Date -->
                            <div class="d-flex align-items-center justify-content-between my-1 fs-small">
                                Order Date:
                                <span>{{ order.order_date|date:'H:i d/m/Y' }}</span>
                            </div>
                            <!-- Order Total -->
                            <div class="d-flex align-items-center justify-content-between mt-1 mb-3 fs-small">
                                Grand Total:
                                <span>£{{ order.grand_total }}</span>
                            </div>
                            <!-- Order Details -->
                            <div id="collapse_{{ order.order_number }}" class="collapse">
                                <!-- Order Quantity -->
                                <hr class="hr-black mt-0 mb-3">
                                {% for item in order.lineitems.all %}
                                    <div class="mb-3">
                                        <!-- Item Details -->
                                        <div class="d-flex align-items-center justify-content-between">
                                            {{ item.product.name }}
                                            <span class="text-end fs-small">Price: £{{ item.product.price }}</span>
                                        </div>
                                        <!-- Size -->
                                        {% if item.product_size %}
                                            <div class="d-flex align-items-center justify-content-between my-1 fs-small">
                                                Size:
                                                <span>{{ item.get_product_size_display|capfirst }}</span>
                                            </div>    
                                        {% endif %}
                                        <!-- Side -->
                                        {% if item.product_side %}
                                            <div class="d-flex align-items-center justify-content-between my-1 fs-small">
                                                Side:
                                                <span>{{ item.get_product_side_display|capfirst }}</span>
                                            </div>
                                        {% endif %}
                                        <!-- Gender -->
                                        {% if item.product_gender %}
                                            <div class="d-flex align-items-center justify-content-between my-1 fs-small">
                                                    Gender:
                                                    <span>{{ item.get_product_gender_display|capfirst }}</span>
                                            </div>
                                        {% endif %}
                                        <!-- Price & Quantity -->
                                        <div class="d-flex align-items-center justify-content-between my-1 fs-small">
                                            Quantity:
                                            <span>{{ item.qty }}</span>
                                        </div>
                                        {% if not forloop.last %}
                                            <hr class="mt-3 mb-0">
                                        {% endif %}
                                    </div>
                                {% endfor %}
                            </div>
                            <button class="view-order m-0 p-0 border-0 bg-white d-block w-100 purple-hover" type="button" data-bs-toggle="collapse" data-bs-target="#collapse_{{ order.order_number }}" aria-expanded="false" aria-controls="collapse_{{ order.order_number }}" aria-label="Button to toggle (expand and collapse) order details for historic order number {{ order.order_number }}">
                                <i class="fas fa-caret-down"></i>
                                <i class="fas fa-caret-up d-none"></i>
                            </button>
                        {% endfor %}
                    {% else %}
                            <p class="fs-small">You have not placed any orders yet.</p>
                            <a href="{% url 'products' %}" class="btn btn-green py-2 mt-3 w-100">
                                <h5 class="mb-0">
                                    <i class="fas fa-tag pe-1"></i>Continue Shopping
                                </h5>
                            </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block postload_js %}
    {{ block.super }}
    <script type="text/javascript">
        // Correct the placeholder (font) colour in the default country input.
        var countrySelected = $('#id_default_country').val();
        if(!countrySelected) {
            $('#id_default_country').css('color', '#aab7c4');
        }
        $('#id_default_country').change(function() {
            countrySelected = $(this).val();
            if(!countrySelected) {
                $(this).css('color', '#aab7c4');
            } else {
                $(this).css('color', '#04080F');
            }
        });

        // Toggle the up/down arrows visibility in the Order History.
        $('.view-order').click(function() {
            $(this).children('i').toggleClass('d-none');
        });
    </script>
{% endblock %}