home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home')
]

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
]

stumps_and_studs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('basket/', include('basket.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from decimal import Decimal
from django.conf import settings

from django_countries.fields import CountryField

from products.models import Product
from profiles.models import UserProfile


class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(
        UserProfile, on_delete=models.SET_NULL,
        null=True, blank=True, related_name='orders')
    order_date = models.DateTimeField(auto_now_add=True)
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    county = models.CharField(max_length=80, null=True, blank=True)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    country = CountryField(
        blank_label='Country - Please Select *', null=False, blank=False)
    delivery_cost = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    original_basket = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(
        max_length=254, null=False, blank=False, default='')

    def _generate_order_number(self):
        """ Generate a random and unique order number using UUID. """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """ Update order total & grand total of order
        each time a new item is added to order. """
        self.order_total = self.lineitems.aggregate(
            Sum('lineitem_total'))['lineitem_total__sum'] or 0
        self.delivery_cost = settings.STANDARD_DELIVERY_COST
        self.grand_total = self.order_total + Decimal(str(self.delivery_cost))
        self.save()

    def save(self, *args, **kwargs):
        """ Overide the original save method to set the order number if
        it doesn't have one already. """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    size_choices = [
        (None, 'No Side'),
        ('jr', 'Junior'),
        ('xs', 'Extra Small'),
        ('s', 'Small'),
        ('m', 'Medium'),
        ('l', 'Large'),
        ('xl', 'Extra Large'),
    ]
    side_choices = [
        (None, 'No Side'),
        ('right', 'Right-Handed'),
        ('left', 'Left-Handed'),
    ]

    gender_choices = [
        (None, 'No Gender'),
        ('male', 'Male'),
        ('female', 'Female'),
    ]

    order = models.ForeignKey(
        Order, null=False, blank=False,
        on_delete=models.CASCADE, related_name='lineitems')
    product = models.ForeignKey(
        Product, null=False, blank=False, on_delete=models.CASCADE)
    product_size = models.CharField(
        max_length=2, choices=size_choices,
        default=None, blank=True, null=True)  # "", JR, XS, S, M, L, XL
    product_side = models.CharField(
        max_length=12, choices=side_choices,
        default=None, blank=True, null=True)  # "", right, left
    product_gender = models.CharField(
        max_length=10, choices=gender_choices,
        default=None, blank=True, null=True)  # "", male, female
    qty = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False,
        blank=False, editable=False)

    def save(self, *args, **kwargs):
        """ Overide the original save method to set the
        lineitem total and update the order total. """
        self.lineitem_total = self.product.price * self.qty
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/models.py
from django.db import models


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Sport(models.Model):
    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    desc = models.TextField()
    sport = models.ForeignKey(
        'Sport', null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey(
        'Category', null=True, blank=True, on_delete=models.SET_NULL)
    has_sizes = models.BooleanField(default=False, null=True, blank=True)
    has_side = models.BooleanField(default=False, null=True, blank=True)
    has_gender = models.BooleanField(default=False, null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rrp = models.DecimalField(max_digits=6, decimal_places=2)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.db.models import Q
from django.db.models.functions import Lower
from .models import Product, Category, Sport


def all_products(request):
    """ A view to show all products including sorting and search queries. """

    products = Product.objects.all()
    query = None
    categories = None
    sports = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sort = request.GET['sort']
            sortkey = sort
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sortkey == 'category':
                sortkey = 'category__name'
            if sortkey == 'sport':
                sortkey = 'sport__name'

            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'sport' in request.GET:
            sports = request.GET['sport'].split(',')
            products = products.filter(sport__name__in=sports)
            sports = Sport.objects.filter(name__in=sports)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(
                    request, "You didn't enter any search criteria.")
                return redirect(reverse('products'))

            queries = Q(name__icontains=query) | Q(desc__icontains=query)
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sports': sports,
        'current_sorting': current_sorting,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """ A view to show individual product details. """

    product = get_object_or_404(Product, pk=product_id)

    context = {
        'product': product,
        'toast_basket_preview': True,
    }

    return render(request, 'products/product_detail.html', context)

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}
{% block head_title %}| {{ product.name }}{% endblock %}

{% block extra_meta %}
    <meta name="description" content="Stumps & Studs - view our range of the latest sports equipment, clothing and footwear.">
{% endblock %}

{% block content %}
    <div class="container-fluid px-3 px-sm-5 py-3">
        <div class="row">
            <div class="col-12 p-3 fs-small">
                <!-- Branch Menu -->
                <a href="{% url 'home' %}" class="text-decoration-underline">Home</a> > 
                <a href="{% url 'products' %}?category={{ product.category }}" class="text-decoration-underline">{{ product.category|capfirst }}</a> > 
                <a href="{% url 'products' %}?sport={{ product.sport }}" class="text-decoration-underline">{{ product.sport|capfirst }}</a> > 
                {{ product.name|capfirst }}
            </div>
        </div>
        <!-- Product -->
        <div class="row">
            <!-- Product Image -->
            <div class="col-md-6 py-3 px-0 px-md-3">
                <h4 class="d-md-none">{{ product.name }}</h4>
                <div class="card border-0 rounded-0">
                    {% if product.image %}
                        <a class="text-center" href="{{ product.image.url }}" target="_blank" rel="noreferrer">
                            <img class="product-image" src="{{ product.image.url }}" alt="{{ product.name }}">
                        </a>
                    {% else %}
                        <img class="product-image" src="{% static 'media/noimage.png' %}" alt="{{ product.name }}">
                    {% endif %}
                </div>
            </div>
            <!-- Product Details -->
            <div class="col-md-6 py-3 px-0 px-md-3">
                <div class="p-3">
                    <h4 class="d-none d-md-block mb-3">{{ product.name }}</h4>
                    <!-- Price & RRP -->
                    <div class="d-flex flex-row align-items-center justify-content-between mb-2">
                        <span><strong>Price:</strong> £{{ product.price }}</span>
                        {% if product.price < product.rrp %}
                            <span class="text-end"><strong>RRP: </strong><s>£{{ product.rrp }}</s></span>
                        {% endif %}
                    </div>
                    <!-- Description -->
                    <div class="mb-2">
                        <div><strong>Description:</strong></div>
                        <div>{{ product.desc }}</div>
                    </div>
                    <form method="POST" action="{% url 'add_to_basket' product.id %}">
                        {% csrf_token %}
                        <!-- Size -->
                        {% with product.has_sizes as sizes %}
                            {% if  sizes %}
                                <div class="d-flex flex-row align-items-center justify-content-between mb-2">
                                    <strong><label for="product_size">Size:</label></strong>
                                    <select class="product-input black-border" name="product_size" id="product_size" aria-label="Select product size">
                                        <option value="jr">Junior</option>
                                        <option value="xs">Extra Small</option>
                                        <option value="s">Small</option>
                                        <option value="m" selected>Medium</option>
                                        <option value="l">Large</option>
                                        <option value="xl">Extra Large</option>
                                    </select>
                                </div>
                            {% endif %}
                        {% endwith %}
                        <!-- Side -->
                        {% with product.has_side as side %}
                            {% if  side %}
                                <div class="d-flex flex-row align-items-center justify-content-between mb-2">
                                    <strong><label for="product_side">Side:</label></strong>
                                    <select class="product-input black-border" name="product_side" id="id_product_side" aria-label="Select product side">
                                        <option value="right" selected>Right-Handed</option>
                                        <option value="left">Left-Handed</option>
                                    </select>
                                </div>
                            {% endif %}
                        {% endwith %}
                        <!-- Gender -->
                        {% with product.has_gender as gender %}
                            {% if  gender %}
                                <div class="d-flex flex-row align-items-center justify-content-between mb-2">
                                    <strong><label for="product_gender">Gender:</label></strong>
                                    <select class="product-input black-border" name="product_gender" id="id_product_gender" aria-label="Select product gender">
                                        <option value="male" selected>Male</option>
                                        <option value="female">Female</option>
                                    </select>
                                </div>
                            {% endif %}
                        {% endwith %}
                        <!-- Qty & Add to Basket -->
                            <div class="d-flex flex-row align-items-center justify-content-between mb-2">
                                <strong><label for="id_qty_{{ product.id }}">Quantity:</label></strong>
                                <div>
                                    <div class="input-group black-border">
                                        <div class="input-group-prepend black-border">
                                            <button class="dec-qty border-0 qty-btn purple-hover" data-item_id="{{ product.id }}" id="dec-qty_{{ product.id }}" aria-label="Decrease product quantity by 1.">
                                                <i class="fas fa-minus"></i>
                                            </button>
                                        </div>
                                        <input class="qty_input border-top-0 border-bottom-0 text-center" type="number" name="qty" value="1" min="1" max="99" data-item_id="{{ product.id }}" id="id_qty_{{ product.id }}">
                                        <label for="id_qty_{{ product.id }}" class="visually-hidden">Quantity of {{ product.name }} in basket.</label>
                                        <div class="input-group-append black-border">
                                            <button class="inc-qty border-0 qty-btn purple-hover" data-item_id="{{ product.id }}" id="inc-qty_{{ product.id }}" aria-label="Increase product quantity by 1.">
                                                <i class="fas fa-plus"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <input type="submit" id="add-to-basket" class="btn btn-green py-2 w-100 border-0 mt-3 ms-0" value="Add to Basket">
                        <!-- Hidden Field -->
                        <input type="hidden" name="redirect_url" value="{{ request.path }}">
                    </form>
                </div>
                <!-- Keep Shopping & Checkout Buttons -->
                <div class="container-fluid px-3">
                    <div class="row">
                        <div class="col-sm-6">
                            <a href="{% url 'view_basket' %}" class="btn btn-green my-3 py-2 w-100"><h5 class="mb-0">
                                <i class="fas fa-lock pe-1"></i>
                                Basket & Checkout</h5>
                            </a>
                        </div>
                        <div class="col-sm-6">
                            <a href="{% url 'products' %}" class="btn btn-orange my-3 py-2 w-100"><h5 class="mb-0">
                                <i class="fas fa-tag pe-1"></i>
                                Continue Shopping</h5>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block postload_js %}
    {{ block.super }}
    {% include 'products/includes/qty_input_script.html' %}
{% endblock %}

products/templates/products/products.html
{% extends "base.html" %}
{% load static %}
{% block head_title %}| Shop{% endblock %}


{% block extra_meta %}
    <meta name="description" content="Stumps & Studs - view our range of the latest sports equipment, clothing and footwear.">
{% endblock %}

{% block content %}
    <div class="container-fluid px-3 px-sm-5 py-3">
        <!-- Title & Filter Options -->
        <div class="row">
            <div class="col-12 px-3 d-flex flex-wrap justify-content-between align-items-center">
                <div class="d-none d-lg-block">
                    <i id="two-wide" class="fas fa-th-large fs-4 purple-hover"></i>
                    <i id="three-wide" class="fas fa-th fs-4 purple-hover d-none"></i>
                </div>
                <div class="text-center">
                    <h2 class="mb-0">Products</h2>
                </div>
                <div>
                    <select name="sort-options" id="sort-options" class="border-0 my-3 dropdown-menu show position-relative bg-dark text-white rounded-0 py-0">
                        <option class="dropdown-item" value="reset" {% if current_sorting == 'None_None' %}selected{% endif %}>Sort By: </option>
                        <option class="dropdown-item" value="price_asc" {% if current_sorting == 'price_asc' %}selected{% endif %}>Price: Low - High</option>
                        <option class="dropdown-item" value="price_desc" {% if current_sorting == 'price_desc' %}selected{% endif %}>Price: High - Low</option>
                        <option class="dropdown-item" value="name_asc" {% if current_sorting == 'name_asc' %}selected{% endif %}>Name: A - Z</option>
                        <option class="dropdown-item" value="name_desc" {% if current_sorting == 'name_desc' %}selected{% endif %}>Name: Z - A</option>
                        <option class="dropdown-item" value="category_asc" {% if current_sorting == 'category_asc' %}selected{% endif %}>Category: A - Z</option>
                        <option class="dropdown-item" value="category_desc" {% if current_sorting == 'category_desc' %}selected{% endif %}>Category: Z - A</option>
                        <option class="dropdown-item" value="sport_asc" {% if current_sorting == 'sport_asc' %}selected{% endif %}>Sport: A - Z</option>
                        <option class="dropdown-item" value="sport_desc" {% if current_sorting == 'sport_desc' %}selected{% endif %}>Sport: Z - A</option>
                    </select>
                </div>
            </div>
        </div>
        <!-- No. of Results -->
        <div class="row">
            <div class="col-12 pt-0 pt-sm-3 px-3 pb-3">
                <!-- Link to All Products -->
                {% if search_term or current_categories or current_sports or current_sorting != 'None_None' %}
                    <small><strong><a href="{% url 'products' %}"><i class="fas fa-arrow-left"></i> All Products</a></strong> | </small>
                {% endif %}
                <!-- Product Count -->
                {% if products|length == 0 %}
                    <small>No products found.</small>
                {% else %}
                    <small>
                        {{ products|length }} 
                        {% if products|length == 1 %}
                            Product
                        {% else %}
                            Products
                        {% endif %}
                        {% if search_term %}
                            found for {{ search_term|capfirst }}
                        {% endif %}
                    </small>
                {% endif %}
            </div>
        </div>
        <!-- Products -->
        <div class="row">
            {% for product in products %}
                <div class="product-container col-12 col-md-6 col-lg-4 p-3">
                    <a href="{% url 'product_detail' product.id %}">
                        <div class="card border-0 rounded-0">
                            {% if product.image %}
                                <img class="card-img-top product-image" src="{{ product.image.url }}" alt="{{ product.name }}">
                            {% else %}
                                <img class="card-img-top product-image" src="{% static 'media/noimage.png' %}" alt="{{ product.name }}">
                            {% endif %}
                            <div class="card-body text-center">
                                <h4 class="mb-1">{{ product.name }}</h4>
                                £{{ product.price }}
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div> 
    </div>
    <!-- Scroll to top of page arrow -->
    <button id="scroll-to-top" class="border-0 p-3" >
        <i class="fas fa-arrow-circle-up fs-1"></i>
    </button>
{% endblock %}

{% block postload_js %}
    {{ block.super}}
    <script type="text/javascript">
        // Adjust Bootstrap grid on large screens, alternate between 2 or 3 columns
        $( '#two-wide' ).click(function() {
            $( '.product-container' ).removeClass( 'col-lg-4', 1000 );
            $( '#three-wide' ).removeClass( 'd-none' );
            $( '#two-wide' ).addClass( 'd-none' );
        });
        $( '#three-wide' ).click(function() {
            $( '.product-container' ).addClass( 'col-lg-4', 1000 );
            $( '#two-wide' ).removeClass( 'd-none' );
            $( '#three-wide' ).addClass( 'd-none' );
        });
        
        // Update the URL when the sort-options selector changes to enable sort & direction options.
        $('#sort-options').change(function() {
            var selector = $(this);
            var currentUrl = new URL(window.location);

            var selectedVal = selector.val();
            if(selectedVal != "reset"){
                var sort = selectedVal.split("_")[0];
                var direction = selectedVal.split("_")[1];

                currentUrl.searchParams.set("sort", sort);
                currentUrl.searchParams.set("direction", direction);

                window.location.replace(currentUrl);
            } else {
                currentUrl.searchParams.delete("sort");
                currentUrl.searchParams.delete("direction");

                window.location.replace(currentUrl);
            }
        });

    </script>
{% endblock %}